<?xml version="1.0" encoding="utf-8"?><Database Name="MyBD" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MyBD.mdf;Integrated Security=True" SettingsObjectName="GestionReservation.Properties.Settings" SettingsPropertyName="MyBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hotels" Member="Hotels">
    <Type Name="Hotel">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NumChambre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>